name: tabula
title: Tabula
version: '1.2.1'
summary: Tabula helps you liberate data tables trapped inside PDF files.
description: |
  If you’ve ever tried to do anything with data provided to you in PDFs,
  you know how painful this is — you can’t easily copy-and-paste rows of
  data out of PDF files. Tabula allows you to extract that data in CSV
  format, through a simple web interface. 

  Caveat - Tabula only works on text-based PDFs, not (image based) scanned 
  documents. If you can click-and-drag to select text in your table in a 
  PDF viewer (even if the output is disorganized trash), then your PDF is 
  text-based and Tabula should work.

  Security Concerns? Tabula is designed with security in mind. Your PDF 
  and the extracted data never touch the net -- when you use Tabula on your 
  local machine, as long as your browser's URL bar says "localhost" or
  "127.0.0.1", all processing takes place on your local machine.
  Even external version checks and the anonymous stats counter have been 
  disabled in the snap.
  
  This snap starts a local web server and then automatically opens a
  browser window. Close the terminal windows to stop the server.  
  It is a community build without support by Tabula's authors.
base: core20  
grade: stable 
confinement: strict
architectures: [amd64]
compression: lzo
license: MIT
environment:
  PATH: $PATH:$SNAP/usr/lib/jvm/java-11-openjdk-amd64/bin

apps:
  tabula:
    command: tabula.sh
    desktop: $SNAPCRAFT_PROJECT_DIR/tabula-desktop/tabula.desktop
    extensions: [gnome-3-38]
    plugs:
      - network
      - network-bind

parts:
  get-source:
    plugin: dump
    source: https://github.com/tabulapdf/tabula/releases/download/v1.2.1/tabula-jar-1.2.1.zip
    source-type: zip
  get-desktop:
    plugin: dump
    source: https://github.com/digidigital/tabula-snap/raw/main/tabula-desktop.zip
    source-type: zip
  packages:
    plugin: nil
    stage-packages:  
      - openjdk-11-jre
      - wget

    override-prime: |
      snapcraftctl prime
      echo '(trap 'kill 0' SIGINT; (wget -tries=20 --retry-connrefused http://127.0.0.1:9999 --waitretry=1 -q -P /dev/null ; xdg-open http://127.0.0.1:9999) & java -Dfile.encoding=utf-8 -Xms256M -Xmx1024M -Dtabula.disable_version_check=1 -Dtabula.disable_notifications=1 -Dwarbler.port=9999 -jar $SNAP/tabula/tabula.jar)' > tabula.sh
      chmod +x tabula.sh

layout:
  /etc/wgetrc:
    bind-file: $SNAP/etc/wgetrc
  /etc/ssl/certs/java/cacerts:
    bind-file: $SNAP/etc/default/cacerts
  /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts:
    bind-file: $SNAP/etc/default/cacerts
